"""Shared rendering constants for Stream Deck+ keys and touch panels."""

from __future__ import annotations

KEY_SIZE = (120, 120)
ICON_SIZE = 80
ICON_PADDING = (KEY_SIZE[0] - ICON_SIZE) // 2

TOUCHSCREEN_WIDTH = 800
TOUCHSCREEN_HEIGHT = 100
PANEL_COUNT = 4

MARGIN_TOP = 4
MARGIN_BOTTOM = 10
MARGIN_LEFT = 4
MARGIN_RIGHT = 4
PANEL_GAP = 4

USABLE_WIDTH = TOUCHSCREEN_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
USABLE_HEIGHT = TOUCHSCREEN_HEIGHT - MARGIN_TOP - MARGIN_BOTTOM

PANEL_WIDTH = (USABLE_WIDTH - (PANEL_COUNT - 1) * PANEL_GAP) // PANEL_COUNT
PANEL_HEIGHT = USABLE_HEIGHT
