"""Safe accessor for the package version.

The real ``deux._version`` module is generated by ``hatch-vcs`` at build
time and is intentionally gitignored. When working from a freshly cloned
source tree (or after ``git clean``) the file may not yet exist, which
would otherwise cause every importer of ``__version__`` to fail with
``ModuleNotFoundError``.

This module centralizes the import with a graceful fallback so that the
package remains importable from a source checkout, and only the version
string is degraded to ``"0.0.0+unknown"``.
"""

from __future__ import annotations

try:
    from deux._version import __version__ as __version__
except ModuleNotFoundError:  # pragma: no cover - exercised only on bare source trees
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
